# Generated by Django 4.1.6 on 2023-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baker',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='baker_images'),
            preserve_default=False,
        ),
    ]
