# Generated by Django 4.2.5 on 2023-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baker', '0003_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='bakers_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
