# Generated by Django 4.2.5 on 2023-11-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baker', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='baker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Baker.baker'),
        ),
    ]
