# Generated by Django 4.2.5 on 2023-11-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baker', '0009_order_baker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='baker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baker_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
