# Generated by Django 4.2.5 on 2023-11-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('receipt', models.CharField(max_length=255)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
            ],
        ),
    ]
