# Generated by Django 4.2.5 on 2023-11-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
    ]
